version: '3.9'
services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - SERVER_URL=${SERVER_URL}
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
